### PR TITLE
Draft: Aptos Streams Documentation

### PR DESCRIPTION
**Pull request by locothedev**
This is a draft

### CODE REVIEW

**Comment by locothedev** [comment]
> 

Yeah we need refinement as I think we need to restructure whole streams docs. Docs are ordered alphabetically correct? I dont like to see aptos so far up before we even talk about what streams in general are

**Comment by YosephKS** [comment]
GM @locothedev @AbhinavMV are you guys planning to add anything to this branch for Aptos streams?

If not I'm going to merge them to my Aptos branch so I can continue working on restructuring and etc to prepare for the launch next week.

**Comment by AbhinavMV** [comment]
yeah sounds good @YosephKS 🙌🏻 
if there are any changes/additions we can add them to your branch or let you know?

**Comment by YosephKS** [comment]
> yeah sounds good @YosephKS 🙌🏻 if there are any changes/additions we can add them to your branch or let you know?

Yes for sure! just simply create the changes and create PR to `add-aptos`. Let's compile all the changes necessary for aptos integration here (including streams) and then push them all at once on the launch date.

For now I'll be merging this PR then 😄

**Review by YosephKS — APPROVED** [review]

**Pull request merged**
